[project]
name = "AOC-charlie"
version = "2025.12.6"
dependencies = [
    "attrs",
    "tqdm",
]

[build-system]
requires = [
    "setuptools",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["20*"]
